

FROM python:3.8

RUN mkdir -p /inferencegraphs
RUN mkdir -p /received
RUN mkdir -p /images
RUN mkdir -p /classes
# RUN apt-get update 
# RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY classes /classes


ADD . /application
WORKDIR ./application

# RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
    
CMD ["python","server.py"]

